LINUXCC = gcc
#BBBCC =
#FSCC =

LINUXFLAGS = -std=c89
#BBBFLAGS = -std=c89
#FSFLAGS = -std=c89

LINUXFILES =
#BBBFILES =
#FSFILES =

LINUXOUTPUT =
#BBBOUTPUT =
#FSOUTPUT =



linux: $(LINUXFILES)
	$(LINUXCC) $(LINUXFLAGS) $(LINUXFILES) -o $(LINUXOUTPUT)
#bbb: $(BBBFILES)
#	$(BBBCC) $(BBBFLAGS) $(BBBFILES) -o $(BBBOUTPUT)
#fs: $(FILES)
#	$(FSCC) $(FSFLAGS) $(FSFILES) -o $(FSOUTPUT)

#all: $(FILES)
#	$(CC) $(CFLAGS) $(FILES) -o $(OUTPUT)

#target: prereq1 prereq2 prereq3
#	command 1
#	command 2
